apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
  labels:
    app: react-frontend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-frontend-app
      version: v1.0.0
  template:
    metadata:
      labels:
        app: react-frontend-app
        version: v1.0.0
    spec:
      containers:
      - name: react-frontend-container
        image: localhost:32000/react-nginx-frontend
        imagePullPolicy: Always
        env:
          - name: VERSION
            value: v1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
  labels:
    app: react-frontend-app
spec:
  type: NodePort
  selector:
    app: react-frontend-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80 
    nodePort: 30007
