apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
  labels:
    app: flask-backend-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-backend-app
  template:
    metadata:
      namespace: flask-backend-app
      labels:
        app: flask-backend-app
    spec:
      containers:
      - name: flask-backend-container
        image: localhost:32000/flask-api-backend
        imagePullPolicy: Always
        env:
        - name: FLASK_ENV
          value: production
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: database-url
---
apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend-app
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30008
  selector:
    app: flask-backend-app