apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
  labels:
    app: flask-backend-app
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30008
  selector:
    app: flask-backend-app