{{- if .Values.enabled }}
apiVersion: v1
kind: {{ .Values.postgres.volume.pv.kind }}
metadata:
  name: {{ .Values.postgres.volume.pv.name }}
  labels:
    type: {{ .Values.postgres.volume.pv.type }}
    app:  {{ .Values.postgres.name }}
spec:
  storageClassName: {{ .Values.postgres.volume.pv.className }}
  accessModes:
    - {{ .Values.postgres.volume.pv.accessMode }}
  capacity:
      storage: {{ .Values.postgres.volume.pv.storage }}
  hostPath:
    path: {{  .Values.postgres.volume.pv.path  }}
{{- end }}