{{- if .Values.enabled }}
apiVersion: v1
kind: {{ .Values.postgres.volume.pvc.kind }}
metadata:
  name: {{ .Values.postgres.volume.pvc.name }}
spec:
  storageClassName: {{ .Values.postgres.volume.pvc.className}}
  accessModes:
    - {{ .Values.postgres.volume.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.volume.pvc.storage }}
{{- end }}