{{- if .Values.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.secret.name }}
data:
  POSTGRES_USER: {{ .Values.postgres.secret.postgresPasswordKey }}
  POSTGRES_PASSWORD: {{ .Values.postgres.secret.postgresPasswordValue }}
  DATABASE_URL: {{ .Values.postgres.secret.postgresUrlValue }}
{{- end }}