{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.service.name }}
  labels: 
    name: {{ .Values.postgres.name }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:             
    app: {{ .Values.postgres.name }}
  ports:
    - protocol: {{ .Values.postgres.service.protocol }}
      port: {{ .Values.postgres.service.port }}       
      targetPort: {{ .Values.postgres.container.port }} 
{{- end }}