kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-database-pv
  labels:
    type: local
    app: postgres-database-app
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/postgres/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-database-pvc
  labels:
    app: postgres-database-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi