apiVersion: v1
kind: Secret
metadata:
  name: microk8s-fullstack-tls-secret
  namespace: default
data:                                                                                                                                                                                                                                    
  tls.crt:
  tls.key:                                                                                                                                                                                         
type: kubernetes.io/tls
