{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.flask.service.name }}
  labels: 
    name: {{ .Values.flask.name }}
spec:
  type: {{ .Values.flask.service.type }}
  ports:
    - port: {{ .Values.flask.service.port }}       
      nodePort: {{ .Values.flask.service.nodeport }} 
  selector:             
    app: {{ .Values.flask.name }}
{{- end }}