enabled: false
replicaCount: 3

flask:
  name: flask-backend-app
  deploymentname: flask-backend-deployment
  container:
    name: flask-backend-container
    image: "localhost:32000/flask-api-backend:registry"
    imagepolicy: Always
  service:
    name: flask-backend-service
    type: NodePort
    port: 5000
    nodeport: 30008
  secret:
    name: flask-secret
    type: Opaque
    dbname: DATABASE_URL
    dburl: cG9zdGdyZXM6Ly9hZG1pbjpwYXNzd29yZDFAbG9jYWxob3N0OjU0MzIvcG9zdGdyZXNkYgo=
  env:
    envname: FLASK_ENV
    envnamevalue: "production"